### ISSUE TITLE
Failing dependency

### ISSUE THREAD

**Issue by noma4i** [cloud66/cx#19]
You have failing dependency:
in `git.go` -> "github.com/cloud66/cloud66" which has `fayecore.go` which refers to `github.com/cloud66/fayego/fayeclient` which has dep to `github.com/serverhorror/uuid` which is dead. "That lay in the house that Jack built." ;)

**Comment by khash** [comment]
Thanks for letting us know. We're going to review this and update the dependencies.

**Comment by lvangool** [comment]
That dependency has been fixed now - please do let us know if you have any other issues!
