### ISSUE TITLE
Add --rm or --keep on the run command (docker)

### ISSUE THREAD

**Issue by xdmx** [cloud66/cx#22]
Currently it's possible to run a command in a specific container, but that container will stick around when the connection ends.

It'd be good having a --rm command to automatically remove it, like docker already does. Or otherwise having it as the default behavior and a --keep flag to keep the container.

Something like `cx run -s Stack --server web --service web --keep 'rails c'`

**Comment by lvangool** [comment]
We'd love to add support for this, but it isn't currently possible due to the way that ContainerNet (underlying weave) creates and attaches to containers. We will keep this open to re-visit when weave has made some advancements in that area (https://github.com/weaveworks/weave/issues/47)

**Comment by lvangool** [comment]
This is handled with the latest version of weave whereby we can include the -rm option
