### ISSUE TITLE
Single line execution of shell command

### ISSUE THREAD

**Issue by ErikDeBruijn** [cloud66/cx#33]
With ssh I can suffix the shell commands. With cx I would like to be able to execute a command on a remote server, just like with ssh.

Is this possible?

**Comment by khash** [comment]
Would this help? http://help.cloud66.com/toolbelt/toolbelt-run-command

**Comment by andruby** [comment]
I've actually solved this by piping the commands to cx STDIN. eg: `echo "uptime && date" | cx ssh -s "stack" server`.

**Comment by khash** [comment]
Thanks @andruby

**Comment by joshuapinter** [comment]
Hey Guys, 

Is there any way to run a command but stay in the ssh session? 

I want to setup a bash alias where it uses the cx toolbelt to ssh into the server and then changes directory to the current Rails release and runs the Rails console. Something like this: 

```bash
$ cx run -s cntral -e staging --server web 'cd /var/deploy/cntral/web_head/current/; bundle exec rails c'
```

Both the `echo` technique and the `cx run` command just exit the ssh session.

**Comment by khash** [comment]
@joshuapinter would it be possible to achieve that with a setup script on the server and `cx ssh`?

**Comment by joshuapinter** [comment]
@khash I can give it a try. What would that look like, do think? 

Thanks.

**Comment by khash** [comment]
This would run on all commands so I don't know if that's what you want but putting a script into the following will run after a login:

`/etc/profile` `~/.bash_profile`, `~/.bash_login` and ~/.profile. Since CX SSH is interactive you can put your script into `~/.bashrc` as well.

**Comment by joshuapinter** [comment]
@khash Gotcha. Yeah, not something I want to run all the time. Was hoping to create an alias in my `.bash_profile` to just ssh into one of my web servers and open the Rails console.

Thanks for the response. I'll keep looking...

**Comment by khash** [comment]
@joshuapinter we're going to add that feature in the new release of cx. Your requirement makes perfect sense

**Comment by joshuapinter** [comment]
@khash Even better, thanks. If you can, please post on here when that gets released and I'll make the update. Cheers!
