### ISSUE TITLE
"x509: failed to load system roots and no roots provided" on OS X

### ISSUE THREAD

**Issue by schrockwell** [cloud66/cx#46]
I am getting the following error when trying to run any remote command:

```
$ cx stacks list
2016/06/14 12:28:22 error: Get https://app.cloud66.com/api/3/stacks.json?page=1: x509: failed to load system roots and no roots provided
```

This is on cx version 0.1.42 and OS X 10.11.5. 

I also tried compiling from source using [these directions](https://github.com/cloud66/cx/wiki/Building-Cloud-66-toolbelt-(cx)-from-source), but the same error occurs. I have also tried rebooting, redownloading the cx binary, deleting `~/.cloud66/cx.json` and re-authenticating, and running with `sudo`.

This error appears to be commonly associated with `cgo` not being enabled or compiled into the binary correctly, but I don't know enough about Go to troubleshoot it.

**Comment by schrockwell** [comment]
This issue still remains on cx 0.1.43. :(

**Comment by schrockwell** [comment]
Problem solved! Something was really screwed up with my Keychain. I blame Xcode.

The fix was in the Keychain Access application: go to the **Keychain Access** menu -> **Preferences...** -> **Reset My Default Keychain**. The **login** keychain was recreated in-place and now `cx` is happy again.

**Comment by khash** [comment]
Thanks for letting us know @schrockwell
