### ISSUE TITLE
Ability to choose backup type

### ISSUE THREAD

**Issue by babakgh** [cloud66/cx#54]
cx backups new should have ability to choose if the backup type is`Text` or `Binary`

**Comment by ciavashkh** [comment]
REFERENCE:
---
https://app.intercom.io/a/apps/gedu1g6a/inbox/siavash@cloud66.com/conversations/8843570108

**Comment by DimitriosLisenko** [comment]
# TEST PLAN

I added a new `backup-type` flag to `cx backups`.

- [ ] Compile `cx` from the latest on the `master` branch
- [ ] Create a new stack on `production`
- [ ] Run `cx backups new --stack $STACK_NAME` - this should create a *BINARY* backup
- [ ] Run `cx backups new --stack $STACK_NAME --backup-type binary` - this should create a *BINARY* backup
- [ ] Run `cx backups new --stack $STACK_NAME --backup-type logical` - this should create a *LOGICAL* backup
- [ ] Run `cx backups new --stack $STACK_NAME --backup-type $SOME_RANDOM_SHIT` - this should raise an error saying that only `logical` and `binary` are acceptable values for the `backup-type` flag.

**Comment by babakgh** [comment]
TEST PASSED

However `logical` isn't the correct term, it should be `text` consistent with the `UI`

**Comment by DimitriosLisenko** [comment]
Changed 'logical' to 'text'

**Comment by ciavashkh** [comment]
I'm against having default for this

**Comment by khash** [comment]
We can't have no default since the CX is an API and is used as it was released. Also we can't change the default backup type for the same reason. CX should carry on working the same way (default being Text) and allow users to switch to Binary if they need.
